// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: generator.proto

package generator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Generator_GenerateUniqueCode_FullMethodName  = "/generator.Generator/GenerateUniqueCode"
	Generator_GenerateUniqueCodes_FullMethodName = "/generator.Generator/GenerateUniqueCodes"
)

// GeneratorClient is the client API for Generator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneratorClient interface {
	GenerateUniqueCode(ctx context.Context, in *GenerateUniqueCodeRequest, opts ...grpc.CallOption) (*Code, error)
	GenerateUniqueCodes(ctx context.Context, in *GenerateUniqueCodesRequest, opts ...grpc.CallOption) (*Codes, error)
}

type generatorClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratorClient(cc grpc.ClientConnInterface) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) GenerateUniqueCode(ctx context.Context, in *GenerateUniqueCodeRequest, opts ...grpc.CallOption) (*Code, error) {
	out := new(Code)
	err := c.cc.Invoke(ctx, Generator_GenerateUniqueCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorClient) GenerateUniqueCodes(ctx context.Context, in *GenerateUniqueCodesRequest, opts ...grpc.CallOption) (*Codes, error) {
	out := new(Codes)
	err := c.cc.Invoke(ctx, Generator_GenerateUniqueCodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorServer is the server API for Generator service.
// All implementations must embed UnimplementedGeneratorServer
// for forward compatibility
type GeneratorServer interface {
	GenerateUniqueCode(context.Context, *GenerateUniqueCodeRequest) (*Code, error)
	GenerateUniqueCodes(context.Context, *GenerateUniqueCodesRequest) (*Codes, error)
	mustEmbedUnimplementedGeneratorServer()
}

// UnimplementedGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedGeneratorServer struct {
}

func (UnimplementedGeneratorServer) GenerateUniqueCode(context.Context, *GenerateUniqueCodeRequest) (*Code, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUniqueCode not implemented")
}
func (UnimplementedGeneratorServer) GenerateUniqueCodes(context.Context, *GenerateUniqueCodesRequest) (*Codes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUniqueCodes not implemented")
}
func (UnimplementedGeneratorServer) mustEmbedUnimplementedGeneratorServer() {}

// UnsafeGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratorServer will
// result in compilation errors.
type UnsafeGeneratorServer interface {
	mustEmbedUnimplementedGeneratorServer()
}

func RegisterGeneratorServer(s grpc.ServiceRegistrar, srv GeneratorServer) {
	s.RegisterService(&Generator_ServiceDesc, srv)
}

func _Generator_GenerateUniqueCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUniqueCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).GenerateUniqueCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Generator_GenerateUniqueCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).GenerateUniqueCode(ctx, req.(*GenerateUniqueCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generator_GenerateUniqueCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUniqueCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).GenerateUniqueCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Generator_GenerateUniqueCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).GenerateUniqueCodes(ctx, req.(*GenerateUniqueCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Generator_ServiceDesc is the grpc.ServiceDesc for Generator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Generator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "generator.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateUniqueCode",
			Handler:    _Generator_GenerateUniqueCode_Handler,
		},
		{
			MethodName: "GenerateUniqueCodes",
			Handler:    _Generator_GenerateUniqueCodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generator.proto",
}
